//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CPSDAL.ModeloDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCTORECETA
    {
        public int pre_id { get; set; }
        public string pre_pro_codigo { get; set; }
        public int pre_correlativo { get; set; }
        public decimal pre_cantidad { get; set; }
        public string pre_usr_creac { get; set; }
        public System.DateTime pre_fec_creac { get; set; }
        public string pre_usr_modif { get; set; }
        public System.DateTime pre_fec_modif { get; set; }
    }
}
